// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/objectbox/file_tag.dart';
import 'models/objectbox/user_preference.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6420280273397156805),
    name: 'FileTag',
    lastPropertyId: const obx_int.IdUid(3, 7947662376134884422),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1079964129057126256),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3689101270339757553),
        name: 'filePath',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 4627900701356382367),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7947662376134884422),
        name: 'tag',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 3785247201596081420),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 802553438266831037),
    name: 'UserPreference',
    lastPropertyId: const obx_int.IdUid(9, 4004233855652818143),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8134669715548537491),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6299629533262048361),
        name: 'stringValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3319213449331022466),
        name: 'intValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4191952925163115257),
        name: 'doubleValue',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1498618922325554597),
        name: 'boolValue',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7094931550144377287),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 2690286472131489868),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6079279981932733498),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4004233855652818143),
        name: 'typeValue',
        type: 5,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 802553438266831037),
    lastIndexId: const obx_int.IdUid(3, 2690286472131489868),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [1534968030676419828],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FileTag: obx_int.EntityDefinition<FileTag>(
      model: _entities[0],
      toOneRelations: (FileTag object) => [],
      toManyRelations: (FileTag object) => {},
      getId: (FileTag object) => object.id,
      setId: (FileTag object, int id) {
        object.id = id;
      },
      objectToFB: (FileTag object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final tagOffset = fbb.writeString(object.tag);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, filePathOffset);
        fbb.addOffset(2, tagOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final tagParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = FileTag(filePath: filePathParam, tag: tagParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserPreference: obx_int.EntityDefinition<UserPreference>(
      model: _entities[1],
      toOneRelations: (UserPreference object) => [],
      toManyRelations: (UserPreference object) => {},
      getId: (UserPreference object) => object.id,
      setId: (UserPreference object, int id) {
        object.id = id;
      },
      objectToFB: (UserPreference object, fb.Builder fbb) {
        final stringValueOffset =
            object.stringValue == null
                ? null
                : fbb.writeString(object.stringValue!);
        final keyOffset = fbb.writeString(object.key);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, stringValueOffset);
        fbb.addInt64(2, object.intValue);
        fbb.addFloat64(3, object.doubleValue);
        fbb.addBool(4, object.boolValue);
        fbb.addOffset(5, keyOffset);
        fbb.addInt64(7, object.timestamp);
        fbb.addInt32(8, object.typeValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final stringValueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final intValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final doubleValueParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final boolValueParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final typeValueParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = UserPreference(
          id: idParam,
          key: keyParam,
          stringValue: stringValueParam,
          intValue: intValueParam,
          doubleValue: doubleValueParam,
          boolValue: boolValueParam,
          typeValue: typeValueParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FileTag] entity fields to define ObjectBox queries.
class FileTag_ {
  /// See [FileTag.id].
  static final id = obx.QueryIntegerProperty<FileTag>(
    _entities[0].properties[0],
  );

  /// See [FileTag.filePath].
  static final filePath = obx.QueryStringProperty<FileTag>(
    _entities[0].properties[1],
  );

  /// See [FileTag.tag].
  static final tag = obx.QueryStringProperty<FileTag>(
    _entities[0].properties[2],
  );
}

/// [UserPreference] entity fields to define ObjectBox queries.
class UserPreference_ {
  /// See [UserPreference.id].
  static final id = obx.QueryIntegerProperty<UserPreference>(
    _entities[1].properties[0],
  );

  /// See [UserPreference.stringValue].
  static final stringValue = obx.QueryStringProperty<UserPreference>(
    _entities[1].properties[1],
  );

  /// See [UserPreference.intValue].
  static final intValue = obx.QueryIntegerProperty<UserPreference>(
    _entities[1].properties[2],
  );

  /// See [UserPreference.doubleValue].
  static final doubleValue = obx.QueryDoubleProperty<UserPreference>(
    _entities[1].properties[3],
  );

  /// See [UserPreference.boolValue].
  static final boolValue = obx.QueryBooleanProperty<UserPreference>(
    _entities[1].properties[4],
  );

  /// See [UserPreference.key].
  static final key = obx.QueryStringProperty<UserPreference>(
    _entities[1].properties[5],
  );

  /// See [UserPreference.timestamp].
  static final timestamp = obx.QueryIntegerProperty<UserPreference>(
    _entities[1].properties[6],
  );

  /// See [UserPreference.typeValue].
  static final typeValue = obx.QueryIntegerProperty<UserPreference>(
    _entities[1].properties[7],
  );
}
